[package]
name = "netboozt"
version = "3.0.0"
description = "Network Optimization Tool for Windows"
authors = ["LOUST <opensource@loust.pro>"]
license = "MIT"
repository = "https://github.com/louzt/NetBoozt_InternetUpgrade"
edition = "2021"
rust-version = "1.70"

# See more keys at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.5", features = [ "dialog-all", "fs-write-file", "shell-execute", "path-all", "fs-read-file", "shell-open", "notification-all", "system-tray", "window-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
thiserror = "1.0"
log = "0.4"
env_logger = "0.10"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["stream", "rustls-tls"], default-features = false }
futures-util = "0.3"
lazy_static = "1.4"

# Windows-specific
[target.'cfg(windows)'.dependencies]
windows = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_Registry",
    "Win32_NetworkManagement_IpHelper",
    "Win32_Networking_WinSock",
] }

[features]
# This feature is used for production builds or when a dev server is not specified
custom-protocol = ["tauri/custom-protocol"]
